name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write service account key to file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESPRSA_5180A }}' > $HOME/gcp-key.json
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcp-key.json
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project esprsa-5180a